# Generated by Django 6.0.7 on 2026-09-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='THE PURSUIT OF SPEED', max_length=200)),
                ('subtitle', models.CharField(default='AN INSIDE LOOK AT WORLD CHAMPIONSHIP FOCUS', max_length=255)),
                ('duration', models.CharField(default='02:45', max_length=20)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='videos/posters/')),
                ('video_url', models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ', help_text='Direct MP4 video URL or YouTube embed URL for lightbox playback')),
                ('is_featured', models.BooleanField(default=True, help_text='Highlighted on homepage film section')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cinematic Video',
                'verbose_name_plural': 'Cinematic Videos',
                'ordering': ['display_order', '-id'],
            },
        ),
    ]
