# Generated by Django 6.0.7 on 2026-09-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('svg_logo', models.TextField(blank=True, help_text='Optional inline SVG logo for crisp monochrome rendering')),
                ('website', models.URLField(blank=True)),
                ('tier', models.CharField(choices=[('TITLE', 'Title Partner'), ('PRINCIPAL', 'Principal Partner'), ('OFFICIAL', 'Official Partner'), ('TECHNICAL', 'Technical Supplier')], default='OFFICIAL', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
