# Generated by Django 6.0.7 on 2026-09-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., THE DRIVER, THE MINDSET', max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='driver/pillars/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Editorial Pillar',
                'verbose_name_plural': 'Editorial Pillars',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='MAX', max_length=100)),
                ('last_name', models.CharField(default='VERSTAPPEN', max_length=100)),
                ('racing_number', models.PositiveIntegerField(default=1)),
                ('permanent_number', models.PositiveIntegerField(default=33)),
                ('team', models.CharField(default='Oracle Red Bull Racing', max_length=150)),
                ('nationality', models.CharField(default='Dutch', max_length=100)),
                ('birth_date', models.DateField(default='1997-09-30')),
                ('birth_place', models.CharField(default='Hasselt, Belgium', max_length=150)),
                ('residence', models.CharField(default='Monte Carlo, Monaco', max_length=150)),
                ('quote', models.CharField(default='Every lap is a test. Not just of the car, but of myself.', max_length=255)),
                ('intro_statement', models.CharField(default='For me, racing is about more than chasing speed — it’s about chasing my absolute limits.', max_length=255)),
                ('biography_intro', models.TextField(default='Max Verstappen was born into motorsport heritage, but his historic trajectory was forged through ironclad dedication, unflinching precision, and an instinctive race craft that redefined Formula 1 standards.')),
                ('biography_full', models.TextField(default='From making history as the youngest driver ever to start an F1 Grand Prix at just 17 years old to commanding four consecutive Formula 1 World Championships, Max Verstappen embodies the pinnacle of modern motorsport engineering and driver focus.')),
                ('portrait_image', models.ImageField(blank=True, null=True, upload_to='driver/portrait/')),
                ('action_image', models.ImageField(blank=True, null=True, upload_to='driver/action/')),
                ('helmet_image', models.ImageField(blank=True, null=True, upload_to='driver/helmet/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Driver Profile',
                'verbose_name_plural': 'Driver Profile',
            },
        ),
        migrations.CreateModel(
            name='DriverStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., WORLD CHAMPIONSHIPS', max_length=100)),
                ('value', models.IntegerField(help_text='Numeric target value for GSAP counter')),
                ('prefix', models.CharField(blank=True, default='', max_length=10)),
                ('suffix', models.CharField(blank=True, default='+', help_text='e.g. + or %', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Driver Statistic',
                'verbose_name_plural': 'Driver Statistics',
                'ordering': ['display_order'],
            },
        ),
    ]
