# Generated by Django 6.0.7 on 2026-09-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(default=2026)),
                ('round_number', models.PositiveIntegerField(help_text='Round 01, 02, etc.')),
                ('name', models.CharField(help_text='e.g. Monaco Grand Prix', max_length=150)),
                ('official_title', models.CharField(blank=True, max_length=200)),
                ('circuit', models.CharField(help_text='e.g. Circuit de Monaco', max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('race_time_utc', models.DateTimeField(help_text='Exact UTC timestamp for countdown calculation')),
                ('laps', models.PositiveIntegerField(default=72)),
                ('circuit_length', models.CharField(default='4.259 km', max_length=50)),
                ('lap_record', models.CharField(blank=True, default='1:11.097', max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('next', 'Next Race (Target)'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
                ('result', models.CharField(blank=True, help_text="e.g. 'P1 — WINNER', 'POLE & WIN'", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='races/')),
                ('circuit_layout_svg', models.TextField(blank=True, help_text='Inline SVG path data for circuit outline')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Race Event',
                'verbose_name_plural': 'Race Events',
                'ordering': ['round_number'],
            },
        ),
    ]
