# Generated by Django 6.0.7 on 2026-09-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='MAX VERSTAPPEN — OFFICIAL WORLD CHAMPION', max_length=200)),
                ('tagline', models.CharField(default='PRECISION UNDER PRESSURE.', max_length=255)),
                ('editorial_statement', models.TextField(default='Speed is only part of the equation. The difference is created through preparation, precision, consistency and the relentless ability to execute when pressure reaches its highest point.')),
                ('hero_statement', models.CharField(default='EVERY LAP IS A TEST.', max_length=150)),
                ('meta_description', models.TextField(default='Official digital experience for 4-time Formula 1 World Champion Max Verstappen. Live race calendar, career history, telemetry statistics, editorial news, and exclusive media.')),
                ('hero_video_url', models.URLField(blank=True, help_text='Direct link or embedded mp4 for hero reel', null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('contact_email', models.EmailField(default='contact@verstappen.com', max_length=254)),
                ('active_season', models.PositiveIntegerField(default=2026)),
                ('footer_text', models.CharField(default='© 2026 MAX VERSTAPPEN. ALL RIGHTS RESERVED.', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('x', 'X / Twitter'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn')], max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['display_order'],
            },
        ),
    ]
