# Generated by Django 6.0.7 on 2026-09-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g. 2015, 2021, 2024', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('KARTING', 'Karting Foundations'), ('JUNIOR', 'Junior Single Seaters'), ('DEBUT', 'Formula 1 Debut'), ('VICTORY', 'First Victory'), ('CHAMPION', 'World Championship'), ('RECORD', 'Historic Record'), ('PRESENT', 'Current Era')], default='CHAMPION', max_length=50)),
                ('description', models.TextField()),
                ('highlight_badge', models.CharField(blank=True, help_text="e.g. 'P1 SPAIN', '19 WINS IN A SEASON'", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='career/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_highlight', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Career Milestone',
                'verbose_name_plural': 'Career Milestones',
                'ordering': ['display_order', 'year'],
            },
        ),
    ]
